#!/bin/bash
# CC0 1.0 Universal 2015 Kenny Rasschaert
# https://creativecommons.org/publicdomain/zero/1.0/
sudo /usr/bin/pacman -Sy >/dev/null 2>&1
sudo /usr/bin/pacman -Qu 2>/dev/null | wc -l 2>/dev/null
