#!/bin/bash
# CC0 1.0 Universal 2015 Kenny Rasschaert
# https://creativecommons.org/publicdomain/zero/1.0/
mount 2>/dev/null | grep -q encfs 2>/dev/null
if [[ $? -eq 0 ]]; then
    echo '🔓'
else
    echo '🔒'
    echo '🔒'
    echo '#c22832'
fi

